### ISSUE TITLE
Possible bug reading negative temperatures

### ISSUE THREAD

**Issue by bkeevil** [JChristensen/DS3232RTC#16]
Haven't tested this but in the function int DS3232RTC::temperature(void) I think:

  return rtcTemp.i >> 6;

should be changed to:

  return rtcTemp.i / 64;

because doing a bit shift will also shift the sign bit and cause an error when reporting negative temperatures.  Dividing by 0x40 will accomplish the same thing without affecting the sign bit.

**Comment by JChristensen** [comment]
I've tested this in the past and it works correctly. For signed integers, GCC replicates the sign bit into the most-significant bit as the bits are shifted. But please go ahead and test it yourself and let me know your results.
However, in doing some research, my understanding of the C++ standard is that this behavior is implementation-dependent. If the library were ported to another platform or if GCC changed its implementation, then there could possibly be an issue.
In that light, your suggested change is a good one and I'll go ahead and make it.
