### ISSUE TITLE
reset alarm

### ISSUE THREAD

**Issue by ran6110** [JChristensen/DS3232RTC#27]
OK, Alarm 1 has triggered and the int pin is set (logic analyzer verified) how do I turn the pin off? It just stays on.

**Comment by JChristensen** [comment]
First, be aware that the RTC continually compares the time registers to the alarm registers and sets its internal alarm flags whenever a match occurs. There is no turning this functionality off. If an internal alarm flag is set, _and_ the alarm interrupt is enabled by calling `alarmInterrupt(ALARM_n, true)` then the INT pin will be asserted.
If an alarm occurs and one then calls the `alarm()` function to reset the internal alarm flag, there is a (perhaps good) possibility that the alarm match still exists causing the internal alarm flag to be immediately set again, and the INT pin to be asserted if enabled.
There are a couple answers to your question: (1) Call `alarmInterrupt(ALARM_1, false)` or (2) Set the alarm to a value that is not going to result in an immediate match, and then call `alarm(ALARM_1)`. In most situations the latter is probably what is desired.
See also issue #6 and the datasheet. HTH.

**Comment by ran6110** [comment]
Thanks
