### ISSUE TITLE
DS1307RTC library compatibility issues

### ISSUE THREAD

**Issue by bperrybap** [JChristensen/DS3232RTC#3]
Finally getting around to finishing up a clock project and starting looking closely
at different libraries.
(I'll be using your DS1307RTC library)

I noticed some DS1307RTC compatibility issues with the library.
I prefer the way your DS3232RTC library works, but it is incompatible with Michael's
DS1307RTC library.

Here is what I have noticed:

1) return values are different.
The return vales in DS1307RTC are true on success and false on failure.
The return values in DS3232RTC are zero on success and an error code on failure.
This is a major difference and makes the library incompatible with each other.
Since if you check true/false zero/non-zero for success, they libraries are
inverted from each other.
I prefer the DS3232RTC way of working where a non zero value means an error
(other than on get() where zero means an error - but i'm ok with that one)
Not sure how to fix this other than you have to pick a direction.

2) Missing API function
Michael's DS1307RTC library has a chipPresent() function that returns whether
or not the RTC module has been detected. This function is missing in DS3232RTC.
I'm not particuarly happy with the way it is implemented in DS1307RTC because
it gets set in read() and write(), which means if you are trying to detect its existence
during initialization you might as well just call get() and look to see if you got
a non zero time_t
But for completeness, you may want to consider adding the function.

3) return value types
DS1307RTC returns booleans from:
set()
read()
write()
while DS3232RTC returns a "byte"

This is related to  number 1 above.
I prefer the way you have done it vs Micheal's boolean since it conveys more information; 
however, it might create an issue if somebody
actually declared a boolean variable and assigned it from return value from the functions.
Not sure I'd change DS3232RTC to use booleans unless you decide to
make the library fully DS1307RTC compatible.

The return value thing is tough  one.
I'd just document it as being similar but not being fully compatible with DS1307RTC.

**Comment by bperrybap** [comment]
Jack,
I just got back to my clock project today and ran into the OSF flag issue
(not being cleared when the time was set)
I need to detect a bad battery and the way to do that is to look at the OSF flag on powerup.
Came back here and was going to create a new bug for it, but noticed that it was fixed already back in January.
I guess the OSF clear issue got lost.
(I probably should have created a separate issue for OSF handling)
Anyway, thanks for the update.

**Comment by ChuckBland** [comment]
I was just reading the spec sheet for the DS3231 chip regarding power. I
don't know if you are using that or the 1307, but you might want to look at
the RST line as well. After reading the specs, I have that chip output on
an input to make sure it is read first, before doing anything to the chip.

FWIW,

Chuck
