### ISSUE TITLE
Add  library to IDE library manager

### ISSUE THREAD

**Issue by bperrybap** [JChristensen/DS3232RTC#35]
Jack,
Could please add this to the IDE library manager?
It is trivial to do, and makes it so easy to add the library to the IDE.
More information here:
You have to create a .properties file:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification
And then ask the Arduino developers to add to the IDE library manager:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

Summary is 
- create the library.properties file
- create a tag whose name matches library version.
- make sure revision number is semver compliant
- create arduino issue to ask arduino devs to add library to library manager

For future releases, just update the .properties file and create new tag
Arduino library manager will automatically discover the new release in about an hour.

One other thing. it would be useful for some environments if you went ahead and fixed issue #30 at the same time as it is trivial and the library "as is" doesn't work in those environments without that update.

**Comment by 1n5aN1aC** [comment]
Yes please!

Your library is very superior to many DS3231 libraries out there, but it's not published tot he library manager, so I struggled with several other libraries that don't have flawless support for the Time library & time_t, but used their own garbage before finally finding yours.

If you want more free publicity, would be very helpful to many people!
