### ISSUE TITLE
day date bug

### ISSUE THREAD

**Issue by mattisback** [JChristensen/DS3232RTC#40]
LINE 219 of file DS3232RTC.cpp

    if (alarmType & 0x01) seconds |= _BV(A1M1);
    if (alarmType & 0x02) minutes |= _BV(A1M2);
    if (alarmType & 0x04) hours |= _BV(A1M3);
    if (alarmType & 0x10) hours |= _BV(DYDT);   //*************
    if (alarmType & 0x08) daydate |= _BV(A1M4);

According to the [datasheet](https://datasheets.maximintegrated.com/en/ds/DS3232.pdf) (page 11), the DYDT bit is on thd daydate alarm register not the hour register.
So it should be:

    if (alarmType & 0x01) seconds |= _BV(A1M1);
    if (alarmType & 0x02) minutes |= _BV(A1M2);
    if (alarmType & 0x04) hours |= _BV(A1M3);
    if (alarmType & 0x10) daydate |= _BV(DYDT);   //*************
    if (alarmType & 0x08) daydate |= _BV(A1M4);

Unless I've misunderstood something.

**Comment by JChristensen** [comment]
That's the way I read it too. Thanks for noticing that!
