### ISSUE TITLE
Why temperature times 4?

### ISSUE THREAD

**Issue by emilydohrem1111** [JChristensen/DS3232RTC#47]
According to the documentation, the `temperature()` function returns the temperature _times_ four. Why is this the case? Won't it be better to just return the temperature directly? I may be missing something here.

Documentation:

```c++
Returns

RTC temperature as degrees Celsius times four. *(int)*
```

**Comment by JChristensen** [comment]
I wanted to keep the code size small. Returning temperature in degrees as an integer loses precision. Returning floating point incurs processing overhead as well as larger code size. By just returning the raw data from the RTC register, the caller can handle it however they want.
