### ISSUE TITLE
'RTC' was not declared in this scope

### ISSUE THREAD

**Issue by Robiv8** [JChristensen/DS3232RTC#49]
sketch_mar30a:13: error: 'RTC' was not declared in this scope
     setSyncProvider(RTC.get);   // the function to get the time from the RTC
                     ^
exit status 1
'RTC' was not declared in this scope

Arduino 1.8.5 say the DS3232 is INKOMPATIBEL?

**Comment by JChristensen** [comment]
What board are you using?

**Comment by JChristensen** [comment]
Do you have the latest release of the library (1.2.0)?

**Comment by Robiv8** [comment]
Hallo,
Yes, I downloaded it here a few hours ago.
Board is NodeMCU 1.0 (ESP-12E) Module its a ESP8266MOD Amica

**Comment by JChristensen** [comment]
For architectures other than AVR, you need to instantiate an RTC object, for example:
```c++
DS3232RTC myRTC;
```
Then use that object for all library calls, for example:
```c++
setSyncProvider(myRTC.get);
```

**Comment by Robiv8** [comment]
Thank you very much for the Info

**Comment by JChristensen** [comment]
The documentation was lacking regarding non-AVR architectures and has now been updated with release 1.2.1.

**Comment by rtek1000** [comment]
Need update the example TimeRTC:

> // Arduino DS3232RTC Library
> // https://github.com/JChristensen/DS3232RTC
> //
> // Example sketch illustrating Time library with Real Time Clock.
> // This example is identical to the example provided with the Time Library,
> // only the #include statement has been changed to include the DS3232RTC library.
> 
> 
> #include <DS3232RTC.h>      // https://github.com/JChristensen/DS3232RTC
> 
> DS3232RTC RTC;  // <--------------------- "Added"
> 
> void setup()
> {
>     Serial.begin(9600);
>     setSyncProvider(RTC.get);   // the function to get the time from the RTC
>     if(timeStatus() != timeSet)
>         Serial.println("Unable to sync with the RTC");
>     else
>         Serial.println("RTC has set the system time");
> }
> 
> void loop()
> {
>     digitalClockDisplay();
>     delay(1000);
> }
> 
> void digitalClockDisplay()
> {
>     // digital clock display of the time
>     Serial.print(hour());
>     printDigits(minute());
>     printDigits(second());
>     Serial.print(' ');
>     Serial.print(day());
>     Serial.print(' ');
>     Serial.print(month());
>     Serial.print(' ');
>     Serial.print(year());
>     Serial.println();
> }
> 
> void printDigits(int digits)
> {
>     // utility function for digital clock display: prints preceding colon and leading 0
>     Serial.print(':');
>     if(digits < 10)
>         Serial.print('0');
>     Serial.print(digits);
> }

**Comment by rtek1000** [comment]
https://github.com/JChristensen/DS3232RTC/blob/master/examples/TimeRTC/TimeRTC.ino

**Comment by JChristensen** [comment]
@rtek1000 why do you reply to a closed issue? What board are you using?
The need to define a DS3232RTC object for non-AVR architectures is documented [here in the README file](https://github.com/JChristensen/DS3232RTC#constructor).

**Comment by kp1851** [comment]
Thanks. I add "DS3232RTC RTC;" and it worked.
