### ISSUE TITLE
Alarm interrupt and square wave.

### ISSUE THREAD

**Issue by rovale** [JChristensen/DS3232RTC#5]
Hi,

I am trying to understand how the alarm interrupts work. So I created a simple example sketch. I am not really sure if the squareWave method plays a role. It appeared that setting it to SQWAVE_NONE sometimes caused the alarm not to go off, SQWAVE_1_HZ gave stable results, but I actually do not see why, because if I want an alarm interrupt on that pin I don't want a square wave. Can you please explain this? Also the alarm seems to go off one millisecond too early.

Regards,
Ronald

``` cpp
/*----------------------------------------------------------------------*
 * Demonstrates usage of the alarm interrupt for alarm 1 and alarm 2.   *
 *                                                                      *
 * 26 December 2014.                                                    *
 *                                                                      *
 * Tested with Arduino 1.5.8, Arduino Nano w/ ATmega328, DS3231.        *
 *                                                                      *
 * This work is licensed under the Creative Commons Attribution-        *
 * ShareAlike 3.0 Unported License. To view a copy of this license,     *
 * visit http://creativecommons.org/licenses/by-sa/3.0/ or send a       *
 * letter to Creative Commons, 171 Second Street, Suite 300,            *
 * San Francisco, California, 94105, USA.                               *
 *----------------------------------------------------------------------*/ 

#include <DS3232RTC.h>        //http://github.com/JChristensen/DS3232RTC
#include <Streaming.h>        //http://arduiniana.org/libraries/streaming/
#include <Time.h>             //http://playground.arduino.cc/Code/Time
#include <Wire.h>             //http://arduino.cc/en/Reference/Wire

#define SQW_PIN 2

void setup(void)
{
    Serial.begin(115200);

    //setSyncProvider() causes the Time library to synchronize with the
    //external RTC by calling RTC.get() every five minutes by default.
    setSyncProvider(RTC.get);
    Serial << "RTC Sync";
    if (timeStatus() != timeSet){
        Serial << " FAIL!";
    }
    Serial << endl;

    printDateTime(now());
    Serial << " --> Current time. (See the SetSerial example for setting the correct date and time)." << endl;

    //Disable the default square wave of the SQW pin.
    //RTC.squareWave(SQWAVE_NONE);

    //Attach an interrupt on the falling of the SQW pin.
    digitalWrite(SQW_PIN, HIGH);
    pinMode(SQW_PIN, INPUT_PULLUP);
    attachInterrupt(INT0, alarmIsr, FALLING);

    //Set an alarm at every 20th second of every minute.
    RTC.setAlarm(ALM1_MATCH_SECONDS, 20, 0, 0, 0);
    RTC.alarmInterrupt(ALARM_1, true);

    //Set an alarm every minute.
    RTC.setAlarm(ALM2_EVERY_MINUTE, 0, 0, 0, 0);
    RTC.alarmInterrupt(ALARM_2, true);
}

volatile boolean alarmIsrWasCalled = false;

void alarmIsr(){
    alarmIsrWasCalled = true;
}

void loop(void)
{
    if (alarmIsrWasCalled){
        if (RTC.alarm(ALARM_1)) {
            printDateTime(now());
            Serial << " --> Alarm 1!" << endl;
        }
        if (RTC.alarm(ALARM_2)) {
            printDateTime(now());
            Serial << " --> Alarm 2!" << endl;
        }
        alarmIsrWasCalled = false;
    }
}

void printDateTime(time_t t)
{
    Serial << ((day(t)<10) ? "0" : "") << _DEC(day(t)) << ' ';
    Serial << monthShortStr(month(t)) << " " << _DEC(year(t)) << ' ';
    Serial << ((hour(t)<10) ? "0" : "") << _DEC(hour(t)) << ':';
    Serial << ((minute(t)<10) ? "0" : "") << _DEC(minute(t)) << ':';
    Serial << ((second(t)<10) ? "0" : "") << _DEC(second(t));
}
```

**Comment by josmanperez** [comment]
Hi! First of all, thanks for this amazing library, its really simple to use. I know it has been a while since the last post, but (and maybe this is a silly question) I'm barely new to this world. With the code above you could trigger and interrupt at a falling level, I have a led on the SQW/INT and its high until the interrupt triggers then it has a falling level.. what I want to achieve (without logical chips) is to have a low level and when the interrupts comes it raise to high level and then comes back to low level.

Is this possible to achieve using only this library and the DS3231?

Thanks in advance.

**Comment by JChristensen** [comment]
Hello Josman, I'm glad that you like the library. This question is more about the DS3231 hardware than about the library. The INT/SQW pin is an open-drain output and the DS3231 does not have an option for inverting the INT signal. See the attached schematic; I assume that you have an arrangement similar to circuit [A] and you want the LED to go on when the alarm is triggered as opposed to going off. If so, then circuit [B] will do this.
The current-limiting resistors are **not** optional. I cannot find a rating in the DS3231 datasheet that tells how much current the INT/SQW pin can safely sink. I would assume that it can only handle perhaps a few milliamps at most. Therefore I would recommend a relatively large resistor; I have shown 1KΩ.
Hope this helps.

![schematic](https://cloud.githubusercontent.com/assets/762571/12003365/474d2124-aae9-11e5-9318-eb1855581b2e.png)

**Comment by t3chguy** [comment]
Sorry to yet again wake an old thread, but this one seems to be a GOTO for Alarm queries, I am wondering whether it is possible (without manually re-setting) to have an Alarm every 20 seconds or every 20 minutes etc. (every multiple of hours/minutes/seconds) without having to wait for the xx:xx:00 ALARM then setting the xx:xx:20 and then the xx:xx:40.
Also, do Alarms persist power cycles, does the module store them and if I don't delete them in my setup routine, will they automatically be configured as they were previously? (Alarms themselves and being attached to the interrupt pin)

Thanks

**Comment by JChristensen** [comment]
Alarm settings will persist through power cycles, the same as the other RTC registers (timekeeping registers, control and status registers, etc.) *if* the RTC has a backup battery.
As for setting the alarms, have a look at Table 2 on p12 of the [datasheet](https://datasheets.maximintegrated.com/en/ds/DS3231.pdf). The alarm registers are continually compared with the timekeeping registers and the alarm will be triggered when one of the following occurs (to use Alarm 1 as an example):
* Alarm once per second
* Alarm when seconds match
* Alarm when minutes and seconds match
* Alarm when hours, minutes, and seconds match
* Alarm when date, hours, minutes, and seconds match
* Alarm when day, hours, minutes, and seconds match

So while we can have an alarm occur once per second, once per minute, once per hour, etc., we cannot do other intervals (every 20 seconds, every 10 minutes) without changing the alarm register after each alarm occurs.
Hope this helps.

**Comment by t3chguy** [comment]
That's great. Thanks @JChristensen for the detailed and prompt response. Covered everything, if I still need other intervals I'll either use the next highest available and divide it down in the software, or just reconfigure the Alarm after each interrupt. 

Thanks!

**Comment by josmanperez** [comment]
Thanks so much for the explanation @JChristensen :+1: , but I still have one more question.. if it possible to use the alarm interrupt without a micro controller? I mean, I'm using the DS3231 to trigger an ESP8266 (ESP01) but I want to be able to use this interrupt with no arduino and with batteries.. when I try this approach, everything works fine until the first interrupt, it seems like the interrupt is trigger and then isn't set again, with the arduino everything works fine.

Do you have any idea?

Again, thank you so much

**Comment by t3chguy** [comment]
That's because it has to be cleared before it can be triggered again @josmanperez

**Comment by josmanperez** [comment]
Thanks @t3chguy , that was I thought... :(

**Comment by plantarum** [comment]
Can I suggest you post the example code for this issue as an actual example for the library? It was really useful in clearing up problems I was having, but it took a lot of googling to actually find it.  Alternatively, I have an even more minimal example, built by stripping out as much as I could from yours and still producing a functional interrupt:

```
/*----------------------------------------------------------------------*
 * Minimal example of setting a recurring alarm with the DS3232 RTC     *
 * Attach an LED to pin 7, which will flash when the alarm fires.       *
 *                                                                      * 
 * Attach the RTC SQ/INT pin to Uno pin 2, with a 10K pull-up to VCC.   *
 * Ard pin A4 -> RTC SDA, Ard A5 -> RTC SCL, 5v -> vcc, GND -> GND      *
 *----------------------------------------------------------------------*/ 
 
#include <DS3232RTC.h>        //http://github.com/JChristensen/DS3232RTC
#include <Time.h>             //http://playground.arduino.cc/Code/Time
#include <Wire.h>             //http://arduino.cc/en/Reference/Wire
#define WAKE_PIN 2
#define LED_PIN 7

void setup(void)
{
    pinMode(LED_PIN, OUTPUT);

    // RTC config:
    RTC.squareWave(SQWAVE_NONE);
    pinMode(WAKE_PIN, INPUT_PULLUP);
    attachInterrupt(INT0, wakeUp, FALLING);  // INT0 == 0 for Atmega328p
   
    RTC.setAlarm(ALM2_EVERY_MINUTE, 0, 0, 0, 1);
    RTC.alarm(ALARM_2);
    RTC.alarmInterrupt(ALARM_2, true);
}

void loop(void)
{
  if(RTC.alarm(ALARM_2)){
    digitalWrite(LED_PIN, HIGH);
    delay(5000);
    digitalWrite(LED_PIN, LOW);
  }
}

void wakeUp (){
  //no-op
}
```

**Comment by t3chguy** [comment]
@plantarum I think your example is misleading, but I think the example @JChristensen provided would be handy within /examples/ I will PR this momentarily.

**Comment by plantarum** [comment]
Thanks @t3chguy. What did I get wrong in my example? I was just thrilled to finally have an apparently working interrupt, I still need to sit down with the DS3232 datasheet to work through each step.

**Comment by t3chguy** [comment]
@plantarum I'm not saying its wrong, but it doesn't make use of the interrupt mechanism at all, you're catching an interrupt trigger yet are doing nothing in the interrupt routine and with your example, the INT pin might as well not be connected as the Alarm is handled by polling.

**Comment by plantarum** [comment]
I suppose it doesn't! That's almost what @JChristensen example does as well, only with only one alarm I didn't need to set the boolean flag in the ISR. My main objective was just to get a visual confirmation that the interrupt was firing as expected, and the arduino was detecting it properly. I'm hoping that with this finally sorted, it will be relatively easy to on to actually doing useful things with the ISR.

Thanks again!

**Comment by t3chguy** [comment]
the boolean flag in the ISR is so that the polling doesn't happen unless it needs to. Whereas your code will waste loads of CPU cycles asking the RTC whether an alarm has Fired. @JChristensen's code will only ask once per Alarm, though it isn't instant, it'll be up to one cycle of the loop function later. But still only once, not polling it as fast as possible as yours is

**Comment by plantarum** [comment]
Aha. I hadn't considered that. Thanks again.

**Comment by t3chguy** [comment]
No problem @plantarum

**Comment by igor-iOS** [comment]
Hi, guys
I'm using a very simple sketch where alarm1 fires every second and alarm2 is not used. This is the only difference from @JChristensen 's code.
I still cannot specify the exact case when it happens, but here's what I found:
If I switch the power of the whole board off/on, randomly in some cases alarms stop firing. If I only switch the power of ds3232 (in real, ds3231) shield, alarms always stop firing in all cases. 
The battery is installed and I've checked the correct work by getting time from the RTC after power off/on and it was definitely correct.
Unfortunately, I don't have an oscilloscope to check whether it's some signal on SQW pin or not.
What I also found is that if we pull of the jumper from SQW to Arduino INT pin, and then reconnect it, program starts to work correctly. This is really strange for me and I cannot find the solution. I checked this on both power from 5V and 3.3V. Maybe I should use pull-up resistors somewhere?

**Comment by romgen** [comment]
Just a followup question: When I use the alarm example and comment out one of the alarms, I still get the messages "alarm1" and "alarm2" [RTC.alarm(ALARM_2) and RTC.alarm(ALARM_1) are TRUE].
Is that normal?

**Comment by JChristensen** [comment]
Both alarm registers are always compared continually with the time registers and the RTC's internal alarm flags, which are tested by `RTC.alarm()` are set accordingly. If ALARM_2 is of no interest, then do not test the flag.

**Comment by antoniofcano** [comment]
Hello,

First of all thanks for this amazing library. I've been fighting with alarm interrupts for two days and I'm totally lost.

`  
#include <DS3232RTC.h>    //http://github.com/JChristensen/DS3232RTC
#include <Time.h>         //http://www.arduino.cc/playground/Code/Time  
#include <Wire.h>         //http://arduino.cc/en/Reference/Wire (included with Arduino IDE)

  /*
     External Interrupts: 3 (interrupt 0), 2 (interrupt 1), 0 (interrupt 2), 1 (interrupt 3) and 7 (interrupt 4).
     These pins can be configured to trigger an interrupt on a low value, a rising or falling edge, or a change
     in value. See the attachInterrupt() function for details. Is not recommended to use pins 0 and 1 as
     interrupts because they are the also the hardware serial port used to talk with the Linux processor.
     Pin 7 is connected to the AR9331 processor and it may be used as handshake signal in future.
     Is recommended to be careful of possible conflicts if you intend to use it as interrupt.
  */
#define RTC_ALARM_PIN 2
bool isInterrupt = false;

void wakeInterrupt() {
  isInterrupt = true;
}

void setup(void)
{
  Serial.begin(9600);
  while (!Serial);

  setSyncProvider(RTC.get);   // the function to get the time from the RTC
  if (timeStatus() != timeSet)
    Serial.println("Unable to sync with the RTC");
  else
    Serial.println("RTC has set the system time");

  RTC.squareWave(SQWAVE_NONE);
  pinMode(RTC_ALARM_PIN, INPUT_PULLUP);
  attachInterrupt(digitalPinToInterrupt(RTC_ALARM_PIN), wakeInterrupt, FALLING);
  
  //Set an alarm at every 20th second of every minute.
  RTC.setAlarm(ALM1_MATCH_SECONDS, 20, 0, 0, 1);    //daydate parameter should be between 1 and 7
  RTC.alarm(ALARM_1);                   //ensure RTC interrupt flag is cleared
  RTC.alarmInterrupt(ALARM_1, true);

  //Set an alarm every minute.
  RTC.setAlarm(ALM2_EVERY_MINUTE, 0, 0, 0, 1);    //daydate parameter should be between 1 and 7
  RTC.alarm(ALARM_2);                   //ensure RTC interrupt flag is cleared
  RTC.alarmInterrupt(ALARM_2, true);
}

void loop(void)
{
  if ( isInterrupt ) {
    Serial.println("isInterrupt...");
    if ( RTC.alarm(ALARM_1) ) {     //has Alarm1 triggered?
      Serial.println("Alarma 1...");
    }
    if ( RTC.alarm(ALARM_2) ) {     //has Alarm1 triggered?
      Serial.println("Alarma 2...");
    }
    isInterrupt = false;
  }
}
`

My hardware is an Arduino YUN and the DS3231 (adafruit-ds3231-precision-rtc-breakout). I've connected the SQW to the digital pin 2 of the arduino board and I tried with the Vin connected with 5V and 3.3V.

The software is the Master branch of the Library.

What happens is simply, the rtc doesn't trigger the interrupt, it goes crazy doing nothing or blocking the loop. I tried with pin 2 and 3, with pullup and without, ....

Any idea! Thanks!!

**Comment by JChristensen** [comment]
@antoniofcano, normally I try to limit discussion here to actual issues with the library and direct user code debugging to the Arduino forum, etc. I do not have a Yun, but the code does work on an Uno, with the following changes:

```c++
@@ -1,3 +1,4 @@
+#include <util/atomic.h>
 #include <DS3232RTC.h> //http://github.com/JChristensen/DS3232RTC
 #include <Time.h> //http://www.arduino.cc/playground/Code/Time
 #include <Wire.h> //http://arduino.cc/en/Reference/Wire (included with Arduino IDE)
@@ -9,8 +10,8 @@ External Interrupts: 3 (interrupt 0), 2 (interrupt 1), 0 (interrupt 2), 1 (inter
  Pin 7 is connected to the AR9331 processor and it may be used as handshake signal in future.
  Is recommended to be careful of possible conflicts if you intend to use it as interrupt.
  */
-#define RTC_ALARM_PIN 2
-bool isInterrupt = false;
+#define RTC_ALARM_PIN 3
+volatile bool isInterrupt = false;
 void wakeInterrupt() {
     isInterrupt = true;
 }
@@ -25,7 +26,7 @@ void setup(void)
         Serial.println("RTC has set the system time");
     RTC.squareWave(SQWAVE_NONE);
     pinMode(RTC_ALARM_PIN, INPUT_PULLUP);
-    attachInterrupt(digitalPinToInterrupt(RTC_ALARM_PIN), wakeInterrupt, FALLING);
+    attachInterrupt(1, wakeInterrupt, FALLING);
     //Set an alarm at every 20th second of every minute.
     RTC.setAlarm(ALM1_MATCH_SECONDS, 20, 0, 0, 1); //daydate parameter should be between 1 and 7
     RTC.alarm(ALARM_1); //ensure RTC interrupt flag is cleared
@@ -40,12 +41,17 @@ void loop(void)
     if ( isInterrupt ) {
         Serial.println("isInterrupt...");
         if ( RTC.alarm(ALARM_1) ) { //has Alarm1 triggered?
-            Serial.println("Alarma 1...");
+            Serial.print(millis());
+            Serial.println(" Alarma 1...");
         }
         if ( RTC.alarm(ALARM_2) ) { //has Alarm1 triggered?
-            Serial.println("Alarma 2...");
+            Serial.print(millis());
+            Serial.println(" Alarma 2...");
+        }
+        ATOMIC_BLOCK(ATOMIC_RESTORESTATE)
+        {
+            isInterrupt = false;
         }
-        isInterrupt = false;
     }
 }
```
Output:
```
RTC has set the system time
isInterrupt...
19685 Alarma 1...
isInterrupt...
59684 Alarma 2...
isInterrupt...
79683 Alarma 1...
isInterrupt...
119682 Alarma 2...
isInterrupt...
139681 Alarma 1...
isInterrupt...
179680 Alarma 2...
isInterrupt...
199680 Alarma 1...
isInterrupt...
239678 Alarma 2...
```

**Comment by antoniofcano** [comment]
Hello,

First of all excuse me for the wrong use of this place. I'll move to this problem to the forum. But before, let me understand what you have done.

 If I'm not wrong first you change the pin/int for the Uno board, but the Yun is 32u4 based and the mapping is different (Int 1 - Pin 2 / Int 0 - Pin 3). I used the function digitalPinToInterrupt for a correct INT  assign.

Board	                                     int.0	int.1	int.2	int.3	int.4	int.5
Uno, Ethernet	                                2	3	 	 	 	 
32u4 based (e.g Leonardo, Micro)	3	2	0	1	7	 

The next thing is the ATOMIC_BLOCK. For me that thing is new, what it does?

Again, a lot of thanks for all!!!

**Comment by JChristensen** [comment]
Hi Antonio, no worries. Yes the pin change was for the Uno board. `ATOMIC_BLOCK` ensures that the code in the block executes without interrupts. The same thing could be done with `cli()` and `sei()` but this is a more general approach ([read more here](http://www.nongnu.org/avr-libc/user-manual/group__util__atomic.html)). When using a variable (like `isInterrupt`) to communicate between an ISR and the main code, there are two important requirements. First, compiler optimization may cause a variable to be stored in a register rather than in RAM. The compiler basically does not know about interrupts and does not understand how such a variable may be updated. Register contents can be lost when an interrupt occurs so it's important to declare such a variable as `volatile`. This tells the compiler that the variable must reside in RAM. Second, we must ensure that all accesses to variables shared with an ISR are "atomic". Because many variable accesses can require multiple instructions, it is possible that the main code could be part way through updating the variable when an interrupt occurs. If the ISR also updates the variable, its contents would be corrupted.
Having said that, there probably would not be a problem in this case since `isInterrupt` is accessed infrequently and the timing is such that there would probably not be a conflict between the ISR and the main code. Furthermore, being a `bool` variable, the `ATOMIC_BLOCK` may not strictly be necessary because the variable in question is a single byte and updates are probably done with a single instruction (but I'd have to check this to be sure). But it's good form to code it properly and that is my preference.
Actually I would add one more `ATOMIC_BLOCK` and that would be where `isInterrupt` is tested with the `if` statement. I would use the `ATOMIC_BLOCK` to copy `isInterrupt` to a local variable in the main code, and then test that variable.
Interrupts can be tricky, and if we get these details wrong, the symptoms can be very confusing and debugging difficult. In a simple situation like this, these changes may not make a difference. If the timing or interrupt frequency were different, or if multi-byte variables were used, it could be a different story. Hope this helps.

**Comment by antoniofcano** [comment]
Amazing explanation, a lot of thanks for the lesson.

Today I take borrowed an Arduino UNO and checked the code before continue, it works as expected. But the Yun still persists with the tricky interrupt. Could it be a hardware question related to the pull_up resistor of the boards?

Reading the arduino doc:
- Arduino yun: ATmega32U4 chip with 20-50 kOhms
- Arduino uno: ATmega328P with 20K pullup

I will continue reading. Again thanks!!

**Comment by JChristensen** [comment]
I think that if you look at the actual datasheets for the microcontrollers, you will find that the specification for the pull-up resistors is identical between the two parts.
