### ISSUE TITLE
Wrong temperature value.

### ISSUE THREAD

**Issue by cotestatnt** [JChristensen/DS3232RTC#57]
The value returned from function `int DS3232RTC::temperature() ` is wrong.
If i run this instruction for example,
`Serial.println(RTC.temperature())`
the function return an int value of about 113°C with a real temperature of 28°C.
Furthermore, the value returned should be a Float and not an Int (the RTC is able to read temperature with a resolution of 0.25°C).

**Comment by JChristensen** [comment]
Working as designed.
See https://github.com/JChristensen/DS3232RTC#returns-14
