### ISSUE TITLE
TimeLib.h in Windows + Arduino 1.8.6

### ISSUE THREAD

**Issue by cherkasovn** [JChristensen/DS3232RTC#59]
Hi,
I installed the library and my Arduino compiler says:
In file included from C:\Users\NC\AppData\Local\Temp\arduino_modified_sketch_863450\TimeRTC.ino:9:0:

{valid path}\libraries\DS3232RTC\src/DS3232RTC.h:25:70: fatal error: TimeLib.h: No such file or directory

compilation terminated.

I suppose I will find a way to solve it, but I wanted to ensure that you are aware of the strange problem.

Thanks for the library!
Nikolay

**Comment by JChristensen** [comment]
Is the prerequisite library installed? https://github.com/PaulStoffregen/Time

**Comment by JChristensen** [comment]
Nothing heard; closing issue.
