### ISSUE TITLE
Alarm1 not working with ALM1_MATCH_HOURS but Alarm2 is

### ISSUE THREAD

**Issue by toogooda** [JChristensen/DS3232RTC#62]
Hi I used the Serial example and altered it so I could wake the Arduino from sleep. I need two alarms per day so thought the build in alarms will be perfect!

It also works without issue on Alarm2 but completly ignors Alarm 1 I see in your documentation that they differ in how they match to Hours and Mins but I have tried everything and can't work out why Alarm1 does not fire.
Any ideas?

>    byte h = time/60;
    byte m = time - (h*60);
    ...
    if (aNum == 1){
      //myAlarms.Alarm1 = time;
      RTC.setAlarm(ALM1_MATCH_HOURS, 0, m, h, 0);  // daydate parameter should be between 1 and 7
      RTC.alarm(ALARM_1);                   // ensure RTC interrupt flag is cleared
      RTC.alarmInterrupt(ALARM_1, true);
      //Serial.println("Alarm1");
   }else{
      //myAlarms.Alarm2 = time;
      RTC.setAlarm(ALM2_MATCH_HOURS, 0, m, h, 0);    // daydate parameter should be between 1 and 7
      RTC.alarm(ALARM_2);                   // ensure RTC interrupt flag is cleared
      RTC.alarmInterrupt(ALARM_2, true);
      //Serial.println("Alarm2");
   }

If I can't resolve it a can just keep setting the second alarm but it would be an ugly work around.

Thanks in advance for your help.

**Comment by JChristensen** [comment]
Hello, if you believe this to be a problem with the library, please provide a [SSCCE](http://www.sscce.org/) and also please be explicit about with the code is expected to do, and what it actually does.

**Comment by JChristensen** [comment]
Nothing heard, closing issue.
