### ISSUE TITLE
Improve paragraph in READE.md

### ISSUE THREAD

**Issue by Koepel** [JChristensen/DS3232RTC#65]
Would it be possible to improve this paragraph in README.md:

_**DS3232RTC** also implements functions to support the additional features of the DS3232 and DS3231. The DS3231 has the same features as the DS3232 except: (1) Battery-backed SRAM, (2) Battery-backed 32kHz output (BB32kHz bit in Control/Status register 0x0F), and (3) Adjustable temperature sensor sample rate (CRATE1:0 bits in the Control/Status register)._

I had to read it a couple of times to understand that the DS3232 has RAM and the DS3231 does not have RAM. It can be confusing that "DS323RTC" is the library and "DS3232" is the chip.

Proposal:

The **DS3232RTC** library also implements functions to support the additional features of the DS3232 and DS3231. The DS3232 has the same features as the DS3231, but the DS3232 has also these extra features:

1. Battery-backed SRAM
2. Battery-backed 32kHz output (BB32kHz bit in Control/Status register 0x0F)
3. Adjustable temperature sensor sample rate (CRATE1:0 bits in the Control/Status register).

**Comment by JChristensen** [comment]
Done. Good suggestion, thank you!
