### ISSUE TITLE
ALM1_MATCH_HOURS

### ISSUE THREAD

**Issue by lucasguanes** [JChristensen/DS3232RTC#70]
Hi

Firstly, thank you Jack for this wonderful library.

I'm trying to set the RTC to 2 alarms per day every day at 8:00 and 17:00. I've read through the documentation in the library but I'm still unsure.

On example 8 we have:

RTC.setAlarm(ALM1_MATCH_HOURS, minute(a1), hour(a1), 1);

I understand if we want to trigger the alarm at 8:00 then we need to say:

RTC.setAlarm(ALM1_MATCH_HOURS, 0, 8, 1);

Can someone please explain to me what the "1" at the end is for please?

Apologies if this is not the right place to ask this question, I have not been able to find information anywhere else.

**Comment by JChristensen** [comment]
See [here](https://github.com/JChristensen/DS3232RTC#setalarmalarm_types_t-alarmtype-byte-seconds-byte-minutes-byte-hours-byte-daydate) in the README file.
The last argument is "dayOrDate: The day of the week or the date of the month."
