### ISSUE TITLE
Update "architectures=avr" to "architectures=*"

### ISSUE THREAD

**Issue by adamgarbo** [JChristensen/DS3232RTC#76]
Hi Jack,

I've been using your DS3232RTC library rather extensively over the past 3 years with Arduinos based on both AVR and SAMD architectures. With the exception of the minor temperature bug we resolved a while back, the library has been extremely reliable. While I know your focus has primarily been on AVR, I'm pretty darn confident that you could update your library.properties to include `architectures=*`. Just my two-cents!

Thanks for a great library!

Cheers,
Adam

**Comment by JChristensen** [comment]
Thanks for your note. I would consider that but I don't have any SAMD boards. I'd want to be in a position to debug issues on various platforms.
