### ISSUE TITLE
Set different I2C pins in RTC.begin() ?

### ISSUE THREAD

**Issue by sheffieldnick** [JChristensen/DS3232RTC#82]
For architectures that can use configurable SDA/SCL pins for I2C communications (eg. the ESP32) is there a recommended way of initialising your library to use those pins? I'd expect something like:
```
#include <DS3232RTC.h>
DS3232RTC RTC(false);
...
RTC.begin(GPIO_NUM_4, GPIO_NUM_16);
```
but `RTC.begin()` doesn't accept optional arguments. Since all it does is call the underlying `Wire.begin()` function, could it just pass on those arguments, if provided? The ESP32 `Wire.begin()` can take up to 3 optional arguments.

At the moment I'm doing this instead, which does work:
```
#include <DS3232RTC.h>
#include <Wire.h>
DS3232RTC RTC(false);
...
// RTC.begin(); don't call this
Wire.begin(GPIO_NUM_4, GPIO_NUM_16);
```
Many thanks

**Comment by JChristensen** [comment]
I don't use the ESP devices and this is probably not something I'll get around to anytime soon; very sorry about that. Actually your workaround seems fine, there's probably not to be improved on over that.
