### ISSUE TITLE
TimeRTC example

### ISSUE THREAD

**Issue by roblatour** [JChristensen/DS3232RTC#89]
The TimeRTC example is missing the line:

DS3232RTC RTC;

and as is it will not compile.

**Comment by JChristensen** [comment]
It compiles OK for an Uno. What board are you using? See the [documentation for the constructor](https://github.com/JChristensen/DS3232RTC#ds3232rtcbool-initi2c). Defining a DS3232RTC object for other architectures is left as an exercise for the user ;-)

**Comment by roblatour** [comment]
An esp32 devkit 1

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by JChristensen** [comment]
Working as advertised then, I guess. While the example could be modified to include an instantiation of a DS3232RTC object, this is not without (a perhaps small) risk. If someone just copies the example, they could end up with an extra, unneeded object. Or the example could be modified with conditional compilation. Pros and cons to all of this, but overall I think it's a small issue. Maybe I will revisit in the future.
