### ISSUE TITLE
DS3232RTC-master on Wemos D1

### ISSUE THREAD

**Issue by lolax80** [JChristensen/DS3232RTC#90]
Hello, 

WARNING: library DS3232RTC-master claims to run on avr architecture(s) and may be incompatible with your current board which runs on esp8266 architecture(s).

Can I use your library with a WEMOS D1 mini?

**Comment by JChristensen** [comment]
Unknown; it may. Try it and see. I don't have that board and my policy is not to advertise my libraries as compatible with boards I do not use and therefore cannot test or debug.
If it does work and if the warning message bothers you, then change [this line](https://github.com/JChristensen/DS3232RTC/blob/6ef565851c0b1b3c5d0d09a4da19b868906cd01a/library.properties#L9) to read as follows:
```c++
architectures=*
```
